apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-pipelines
spec:
  destination:
    namespace: kubeflow
    server: "https://kubernetes.default.svc"
  source:
    path: content/infra/k8s-install/assets/kubeflow/kubeflow-pipelines
    repoURL: "https://github.com/didine13/kubeflow-pipeline.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
